package com.pidzama.comicsdreamsapp.ui.theme

import androidx.compose.ui.unit.dp

val EXTRA_LARGE_PADDING_40 = 40.dp
val LARGE_PADDING_20 = 20.dp
val MEDIUM_PADDING_16 = 16.dp
val PAGING_INDICATOR_WIDTH = 12.dp
val SMALL_PADDING_10 = 10.dp
val EXTRA_SMALL_PADDING_6 = 6.dp

val HEIGHT_HERO_ITEM_BOX = 400.dp
val HEIGHT_NAME_SHIMMER_PLACEHOLDER = 30.dp
val HEIGHT_ABOUT_SHIMMER_PLACEHOLDER = 18.dp
val HEIGHT_RATING_SHIMMER_PLACEHOLDER = 20.dp
val SIZE_IMAGE_ERROR = 150.dp